name: Compile LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest  # Usa una imagen con LaTeX preinstalado

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error TFG.tex
          bibtex TFG || true  # Solo si usas referencias
          pdflatex -interaction=nonstopmode -halt-on-error TFG.tex
          pdflatex -interaction=nonstopmode -halt-on-error TFG.tex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: TFG.pdf
      
      - name: Commit and push compiled PDF
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add TFG.pdf
          git commit -m "Actualización automática del PDF compilado"
          git push

