name: Compile LaTeX Document

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest  # Usa una imagen con LaTeX preinstalado

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error TFG.tex
          bibtex TFG || true  # Solo si usas referencias
          pdflatex -interaction=nonstopmode -halt-on-error TFG.tex
          pdflatex -interaction=nonstopmode -halt-on-error TFG.tex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: TFG.pdf
      
      - name: Commit and push compiled PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add TFG.pdf
          git commit -m "Actualización automática del PDF compilado"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
      - name: Merge changes into main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin main
          git checkout main
          git merge --strategy-option ours ${{ github.sha }} -m "Merge changes from workflow"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main

